default_platform(:ios)

platform :ios do

  desc "Push a new homolog build to TestFlight"
  lane :tests do
    cocoapods
    run_tests(workspace: "ChuckNorrisFacts.xcworkspace",
              scheme: "Domain")
    run_tests(workspace: "ChuckNorrisFacts.xcworkspace",
              scheme: "Facts")
  end

  desc "Push a new homolog build to TestFlight"
  lane :homolog do |options|
    cocoapods
    increment_build_number_xcodeproj(target: 'App')
    build_app(workspace: "ChuckNorrisFacts.xcworkspace", scheme: "App")
    upload_to_testflight(username: options[:username])
  end

  desc "Push and version up a new homolog build to TestFlight"
  lane :homologVersionUp do |options|
    increment_version_number_xcodeproj(xcodeproj: 'App.xcodeproj', target: 'App')
    homolog username:options[:username]
  end

  desc "Push a new homolog build to TestFlight with custom version"
  lane :homologWithCustomVersion do |options|
    increment_version_number_xcodeproj(version_number: options[:version], xcodeproj: 'App.xcodeproj', target: 'App')
    homolog username:options[:username]
  end

  desc "Push a new production build to TestFlight"
  lane :production do |options|
    cocoapods
    increment_build_number_xcodeproj(target: 'AppProd')
    build_app(workspace: "ChuckNorrisFacts.xcworkspace", scheme: "AppProd")
    upload_to_testflight(username: options[:username])
  end

  desc "Push and version up a new production build to TestFlight"
  lane :productionVersionUp do |options|
    increment_version_number_xcodeproj(xcodeproj: 'App.xcodeproj', target: 'AppProd')
    production username:options[:username]
  end

  desc "Push a new production build to TestFlight with custom version"
  lane :productionWithCustomVersion do |options|
    increment_version_number_xcodeproj(version_number: options[:version], xcodeproj: 'App.xcodeproj', target: 'AppProd')
    production username:options[:username]
  end
end