name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Select Xcode 12
      run: sudo xcode-select -switch /Applications/Xcode_12.0.app

    - name: Bundle Install
      run: bundle install

    - name: Run tests
      run: bundle exec fastlane tests
