name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Bundle Update
      run: bundle update
    - name: Run tests
      run: bundle exec fastlane tests
